### ISSUE TITLE
安装到 Docker

### ISSUE THREAD

**Issue by fengwang** [zdhxiong/mdclub#2]
是否可以提供一个 dockerfile?

**Comment by Teeoo** [comment]
```yml
version: '3'
services:
    nginx:
        image: nginx:xxx
        container_name: xxx-nginx
        restart: always    
        ports:    
        - 80:80    
        - 443:443
        links:    #容器链接
        - php
        volumes:
        - /nginx-config:/etc/nginx/conf.d  #nginx配置文件目录
        - oryxtc-volume:/home
    php:
        image: xxx/xxx-php
        container_name: xxx-php
        restart: always
        volumes:
        - oryxtc-volume:/home 
volumes: 
    oryxtc-volume:
        driver: local-persist 
        driver_opts:
            mountpoint: xxx    #项目总目录
```
